### ISSUE TITLE
Bug: Urls ending with questionmark / hashtag are not base64 encoded

### ISSUE THREAD

**Issue by peters** [zckrs/gulp-css-base64#22]
Urls ending with a questionmark / hashtag are not base64 encoded, see [fontawesome](http://fontawesome.io/assets/font-awesome/css/font-awesome.css)

``` css
@font-face {
  font-family: 'FontAwesome';
  src: url('../fonts/fontawesome-webfont.eot?v=4.2.0');
  src: url('../fonts/fontawesome-webfont.eot?#iefix&v=4.2.0') format('embedded-opentype'), url('../fonts/fontawesome-webfont.woff?v=4.2.0') format('woff'), url('../fonts/fontawesome-webfont.ttf?v=4.2.0') format('truetype'), url('../fonts/fontawesome-webfont.svg?v=4.2.0#fontawesomeregular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```
