### ISSUE TITLE
Commented code also being processed

### ISSUE THREAD

**Issue by ank91** [zckrs/gulp-css-base64#34]
For example i have a style.css file with code

```css

/*
.first{
    background: url("../image1.png");
}*/

.second {
    background: url("../image2.jpg");
}

```

This plugin will also process ```image1.png```  and convert it to base64,
I know one can ignore by adding ```/*base64:skip*/```, but commented code should not be processed.
Please fix this, thanks.
